# Configuração CORS para o Supabase
# Define quais origens podem acessar o backend

[cors]
  # Origens permitidas para acessar a API
  allowed_origins = [
    "http://localhost:3000",
    "http://localhost:5173",
    "https://meu-plano-saudavel.vercel.app"
  ]
  
  # Métodos HTTP permitidos 
  allowed_methods = ["GET", "POST", "PUT", "DELETE", "OPTIONS", "PATCH"]
  
  # Cabeçalhos HTTP permitidos
  allowed_headers = [
    "Authorization",
    "Content-Type",
    "Accept",
    "X-Client-Info",
    "apikey"
  ]
  
  # Habilitar suporte a cookies e credenciais
  allowed_credentials = true
  
  # Tempo em segundos que o navegador pode armazenar em cache a resposta pré-voo
  max_age = 3600 