# Configuração CORS para o Supabase
# Estas configurações devem ser aplicadas no painel de controle do Supabase > Configurações > API

[cors]
# Origens permitidas - adicione todos os domínios onde sua aplicação será acessada
allowed_origins = [
  "https://meu-plano-saudavel.vercel.app",
  "http://localhost:3000",
  "https://*-meu-plano-saudavel.vercel.app"
]

# Métodos HTTP permitidos
allowed_methods = ["GET", "POST", "PUT", "DELETE", "OPTIONS"]

# Cabeçalhos permitidos
allowed_headers = [
  "Authorization",
  "Content-Type",
  "Accept",
  "Origin",
  "User-Agent",
  "DNT",
  "Cache-Control",
  "X-Mx-ReqToken",
  "Keep-Alive",
  "X-Requested-With",
  "If-Modified-Since"
]

# Habilitar credenciais (cookies)
allow_credentials = true

# Tempo de cache para preflight requests (OPTIONS)
max_age = 86400 # 24 horas

# Configurações recomendadas para Auth
[auth.cors]
allow_credentials = true
allowed_origins = [
  "https://meu-plano-saudavel.vercel.app",
  "http://localhost:3000",
  "https://*-meu-plano-saudavel.vercel.app"
] 